server:
  port: 8080

hippo:
  storage:
    base-dir: ./workspace
  exiftool:
    path: C:/tools/exiftool/exiftool.exe

spring:
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 10GB
